name: CI

on:
  push:
    branches:
      - main

jobs:
  quality-checks:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run ESLint and fix
        run: npm run lint:fix

      - name: Format with Prettier
        run: npm run format

      - name: Check for remaining ESLint errors
        run: npm run lint

      - name: Check for remaining formatting issues
        run: npm run format:check
